liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # define your filter sets under this option
    filter_sets:
        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        thumb_medium:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [369, 220]
                    mode:          outbound
                    allow_upscale: true
        thumb_180_140:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [180, 140]
                    mode:          outbound
                    allow_upscale: true
        thumb_530_330:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [530, 330]
                    mode:          outbound
                    allow_upscale: true
        thumb_590_300:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [590, 300]
                    mode:          outbound
                    allow_upscale: true
        thumb_550_350:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [550, 350]
                    mode:          outbound
                    allow_upscale: true
        thumb_blog:
            jpeg_quality:          95
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [870, 521]
                    mode:          outbound
                    allow_upscale: true