security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_MEMBER:        ROLE_USER
        ROLE_ADMIN:         ROLE_MEMBER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fse_db_provider:
            entity: { class: App\Entity\Users, property: email }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            form_login:
                login_path: signin_page
                check_path: signin_page
            logout:
                path: security_logout
                target: /

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
          - { path: ^/secure/signin$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_channel%' }
          - { path: ^/secure/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_channel%' }
          - { path: ^/secure/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_channel%' }
          - { path: ^/admin, roles: ROLE_ADMIN , requires_channel: '%secure_channel%'}
          - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%secure_channel%' }

